### PR TITLE
use HTTPS.

### PR DESCRIPTION
**Pull request by bgentry**
Use HTTPS for all URLs.

### CODE REVIEW

**Comment by herval** [comment]
@bgentry did you try these out? It seems at least one of these doesn't work (the `read_symbols` one returns an error on https)

**Comment by bgentry** [comment]
I did not try them all out, sorry. Only using the quotes stuff on my
project.

**Comment by herval** [comment]
It seems some of the endpoints don't support https (eg the d.yimg.com/autoc.finance.yahoo.com/autoc one).
Could you rebase and check that? (files changed a lot in the latest release)

**Comment by bcoles** [comment]
It seems all servers support HTTPS except the d.yimg.com. I've created a new PR #30 forked from the most recent code base.

**Pull request closed without merging**
