### PR TITLE
fix historical quotes

### PR DESCRIPTION
**Pull request by zolrag13**
closes https://github.com/herval/yahoo-finance/issues/42

Fixed historical quotes following the snippet on https://github.com/herval/yahoo-finance/issues/42#issuecomment-308550444.

I changed `trade_date` to `date`. If that's a problem, I can change it back.

### CODE REVIEW

**Comment by zolrag13** [comment]
It looks like Yahoo is now only displaying 100 results and using infinite scrolling to show the rest. I will make change to the PR to be able to get all data at once.

**Comment by zolrag13** [comment]
For people using `weekly` and `monthly` data, they might want to improve on this. I am not interested in these interval but I have put something that works even though it's not super clean.

**Comment by herval** [comment]
interesting change

could you update the docs? I'd keep the :trade_date as-is for backward compatibility too. We might want to release this as a new major version, as it's a bit of a big change

**Comment by zolrag13** [comment]
You are right `trade_date` is better. Will do!

**Comment by zolrag13** [comment]
@herval could you please give the PR another look?

**Pull request merged**
