### PR TITLE
added companies, sectors and industries

### PR DESCRIPTION
**Pull request by zolrag13**
I have added several functions to get the list of companies by market, companies, industries and sectors. I don't know if other people are interested but I use it in my code so I figured it might be helpful to others.

### CODE REVIEW

**Comment by herval** [comment]
hey,

would you mind adding tests & docs for this? thx!

**Comment by zolrag13** [comment]
Hey, sure I will take care of it asap. 👍

**Comment by zolrag13** [comment]
@herval could you give this PR a second look? Thank you.

**Comment by herval** [comment]
thank you for the contributions! Great work :-)

**Pull request merged**
